### ISSUE TITLE
plugin doesn't work

### ISSUE THREAD

**Issue by rocifier** [kevinrambaud/serverless-functions-base-path#193]
Hi, I have installed the plugin in my project's folder `C:\Repos\contact-center-backend\uoa-connect` and then my function is defined in `./serverless/green/serverless.yml`
My source code for the function is in `./src/queryIndex.js`

My function is defined in serverless.yml like this:
```
plugins:
  - serverless-functions-base-path
  
custom:
  functionsBasePath: ../../src

functions:
  queryIndex:
    handler: queryIndex.handler
```

When I CD into `./serverless/green/ ` and run `serverless invoke local --stage test -f queryIndex -p '../../test/queryIndex-events.json' --profile saml` I get the error:

`Error: Cannot find module 'C:\Repos\contact-center-backend\uoa-connect\serverless\green\queryIndex'`
